apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - certificate-user.yaml
  - certificate-admin.yaml
  - deployment-user.yaml
  - deployment-admin.yaml
  - ingress-user.yaml
  - ingress-admin.yaml
  - db-credentials-sync.yaml
  - secrets/acruet-oidc.yaml
  - secrets/acruet-smtp.yaml
