---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: plex-config-pvc
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 32Gi
  storageClassName: csi-rbd-sc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: plex-transcode-pvc
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 32Gi
  storageClassName: csi-rbd-sc
---
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: plex-media-pvc
# spec:
#   accessModes:
#     - ReadWriteOnce
#   volumeMode: Filesystem
#   resources:
#     requests:
#       storage: 9Ti
#   storageClassName: csi-rbd-sc
