apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base
  - image-automation.yaml
images:
  - name: sbwise/acruet-user
    newTag: 1.3.0 # {"$imagepolicy": "flux-system:acruet-user:tag"}
  - name: sbwise/acruet-admin
    newTag: 1.3.0 # {"$imagepolicy": "flux-system:acruet-admin:tag"}
