server {
    listen       80;
    listen  [::]:80;
    server_name  localhost;

    root   /usr/share/nginx/html;
    index  index.html index.htm;

    location / {
        try_files $uri $uri/ =404;
    }

    location /.well-known/openid-configuration {
        default_type application/json;
        add_header Content-Type application/json always;
        add_header Cache-Control: no-cache always;
    }

    location /keys.json {
        default_type application/json;
        add_header Content-Type application/json always;
        add_header Cache-Control: no-cache always;
    }
}
