apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: gateway-internal
  namespace: kgateway-system
spec:
  gatewayClassName: kgateway
  infrastructure:
    parametersRef:
      name: gateway-internal
      group: gateway.kgateway.dev
      kind: GatewayParameters
  listeners:
    - name: http
      protocol: HTTP
      port: 80
      allowedRoutes:
        namespaces:
          from: All
    - name: https
      protocol: HTTPS
      port: 443
      tls:
        mode: Terminate
        certificateRefs:
          - name: gateway-edge-tls
            kind: Secret
            group: ""
      allowedRoutes:
        namespaces:
          from: All
    - name: https-acruet-admin
      protocol: HTTPS
      port: 443
      hostname: acruet-admin.home.bradandmarsha.com
      tls:
        mode: Terminate
        certificateRefs:
          - name: acruet-admin-certificate
            namespace: acruet
            kind: Secret
            group: ""
      allowedRoutes:
        namespaces:
          from: All
    - name: https-flux-web
      protocol: HTTPS
      port: 443
      hostname: flux-web.home.bradandmarsha.com
      tls:
        mode: Terminate
        certificateRefs:
          - name: certificate-flux-web
            namespace: flux-system
            kind: Secret
            group: ""
      allowedRoutes:
        namespaces:
          from: All
    - name: https-ceph-dashboard
      protocol: HTTPS
      port: 443
      hostname: ceph-dashboard.home.bradandmarsha.com
      tls:
        mode: Terminate
        certificateRefs:
          - name: certificate-ceph-dashboard
            namespace: rook-ceph
            kind: Secret
            group: ""
      allowedRoutes:
        namespaces:
          from: All
    - name: https-grafana-dashboard
      protocol: HTTPS
      port: 443
      hostname: grafana-dashboard.home.bradandmarsha.com
      tls:
        mode: Terminate
        certificateRefs:
          - name: certificate-grafana-dashboard
            namespace: monitoring
            kind: Secret
            group: ""
      allowedRoutes:
        namespaces:
          from: All
