apiVersion: gateway.kgateway.dev/v1alpha1
kind: GatewayParameters
metadata:
  name: gateway-internal
  namespace: kgateway-system
spec:
  kube:
    service:
      type: LoadBalancer
      externalTrafficPolicy: Local
      extraAnnotations:
        metallb.io/address-pool: home-pool-internal
