apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - issuer.yaml
  - certificate-edge-tls.yaml
  - gateway-parameters-public.yaml
  - gateway-parameters-internal.yaml
  - gateway-public.yaml
  - gateway-internal.yaml
