apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../base/26.7.0

patches:
  - target:
      kind: Deployment
      name: keycloak-operator
    patch: |
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: keycloak-operator
      spec:
        template:
          spec:
            containers:
              - name: keycloak-operator
                resources:
                  requests:
                    cpu: 25m
                    memory: 392Mi
                  limits:
                    cpu: 700m
                    memory: 510Mi
