apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - certificate.yaml
  - ingress.yaml
  - db-credentials-sync.yaml
  - keycloak.yaml
  - realm-import.yaml
  - oidc-client-acruet.yaml
  - oidc-client-acruet-admin.yaml
  - secrets/acruet-oidc-client.yaml
  - secrets/acruet-admin-oidc-client.yaml
  - secrets/keycloak-admin.yaml
