apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - certificate.yaml
  - httproute.yaml
  - referencegrant-gateway-tls.yaml
  - db-credentials-sync.yaml
  - keycloak.yaml
  - realm-import.yaml
  - oidc-client-acruet.yaml
  - oidc-client-acruet-admin.yaml
  - secrets/acruet-oidc-client.yaml
  - secrets/acruet-admin-oidc-client.yaml
  - secrets/keycloak-admin.yaml
  - secrets/keycloak-smtp.yaml

replacements:
  - source:
      kind: Secret
      name: keycloak-smtp
      fieldPath: stringData.host
    targets:
      - select:
          kind: KeycloakRealmImport
          name: wise-k8s-realm
        fieldPaths:
          - spec.realm.smtpServer.host
  - source:
      kind: Secret
      name: keycloak-smtp
      fieldPath: stringData.port
    targets:
      - select:
          kind: KeycloakRealmImport
          name: wise-k8s-realm
        fieldPaths:
          - spec.realm.smtpServer.port
  - source:
      kind: Secret
      name: keycloak-smtp
      fieldPath: stringData.from
    targets:
      - select:
          kind: KeycloakRealmImport
          name: wise-k8s-realm
        fieldPaths:
          - spec.realm.smtpServer.from
  - source:
      kind: Secret
      name: keycloak-smtp
      fieldPath: stringData.username
    targets:
      - select:
          kind: KeycloakRealmImport
          name: wise-k8s-realm
        fieldPaths:
          - spec.realm.smtpServer.user
  - source:
      kind: Secret
      name: keycloak-smtp
      fieldPath: stringData.password
    targets:
      - select:
          kind: KeycloakRealmImport
          name: wise-k8s-realm
        fieldPaths:
          - spec.realm.smtpServer.password
