apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base/v1.14.1

patches:
  - target:
      kind: Service
      name: ingress-nginx-controller
    path: patches/controller-lb.yaml
  - target:
      kind: Deployment
      name: ingress-nginx-controller
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/args
        value:
          - "/nginx-ingress-controller"
          - "--election-id=ingress-nginx-leader"
          - "--controller-class=k8s.io/ingress-nginx"
          - "--ingress-class=nginx"
          - "--configmap=$(POD_NAMESPACE)/ingress-nginx-controller"
          - "--validating-webhook=:8443"
          - "--validating-webhook-certificate=/usr/local/certificates/cert"
          - "--validating-webhook-key=/usr/local/certificates/key"
  - target:
      kind: ValidatingWebhookConfiguration
      name: ingress-nginx-admission
    patch: |-
      - op: add
        path: /webhooks/0/matchConditions
        value:
          - name: nginx
            expression: "object.spec.ingressClassName == 'nginx'"
