apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base
  - image-automation.yaml
images:
  - name: sbwise/pms-docker
    newTag: 2.1.3 # {"$imagepolicy": "flux-system:pms-docker:tag"}
