---
apiVersion: v1
kind: Namespace
metadata:
  name: namecheap-ddns
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: namecheap-ddns
  namespace: namecheap-ddns
spec:
  selector:
    matchLabels:
      app: namecheap-ddns
  template:
    metadata:
      labels:
        app: namecheap-ddns
        secret-name: namecheap-ddns
    spec:
      containers:
      - name: namecheap-ddns
        image: sbwise/namecheap-ddns:1.0.0
        resources:
          limits:
            memory: '32Mi'
            cpu: '50m'
        env:
        - name: NC_HOST
          value: 'home'
        - name: NC_DOMAIN
          value: 'bradandmarsha.com'
        envFrom:
          - secretRef:
              name: namecheap-ddns
