apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: external-dns

resources:
  - namespace.yaml
  - ../base/v0.20.0

patches:
  - target:
      kind: Deployment
    path: patches/aws-region.yaml
  - target:
      kind: Deployment
    path: patches/args.yaml
  - target:
      kind: Deployment
    path: patches/gateway-api-source.yaml
  - target:
      kind: ClusterRole
      name: external-dns
    path: patches/gateway-api-rbac.yaml
  - target:
      kind: ServiceAccount
    path: patches/aws-role.yaml
