apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: external-dns

resources:
  - namespace.yaml
  - ../base/v0.20.0

patches:
  - target:
      kind: Deployment
    path: patches/aws-creds.yaml
  - target:
      kind: Deployment
    path: patches/args.yaml
