apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: acruet-cnpg
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./iac/kustomize/acruet-cnpg/overlays
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
    - name: cloud-native-pg
