apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: capacitor
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./iac/kustomize/capacitor/overlays
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
