apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - aws-iam-oidc-provider.yaml
  - cert-manager.yaml
  - cloud-native-pg.yaml
  - external-dns.yaml
  - flask-hello-world.yaml
  - ingress-nginx-internal.yaml
  - ingress-nginx-public.yaml
  - keycloak-cnpg.yaml
  - kube-prometheus-stack.yaml
  - lets-encrypt.yaml
  - media.yaml
  - metal-lb.yaml
  - plex.yaml
  - plex-cnpg.yaml
  - pod-identity-webhook.yaml
  - rook.yaml
  - route53-ddns.yaml
  - wise-home-index.yaml
