apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: wise-home-index
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./iac/kustomize/wise-home-index/overlays
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
    - name: kgateway
