# Service account secret for a-cruet admin WAR -> Keycloak Admin API (Phase 6).
apiVersion: v1
kind: Secret
metadata:
    name: acruet-admin-api
    namespace: acruet
type: Opaque
stringData:
    client-secret: ENC[AES256_GCM,data:xCUT6X0Ngdn9seUfsLuxDnmqc+comUeoAVDM93TuDbrXVVHIKlrkeNYAcdM=,iv:QqLraIy7dqQLKMaFubPCGORnkoby4ws85wxZ0SVTT7E=,tag:iYP1IhZ69kFHLmESO/Kiow==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:us-east-2:712671171381:alias/sops
          created_at: "2026-07-15T03:04:42Z"
          enc: AQICAHhjc7KqbSU4p0/AUwvgncJOvdI1500sgVLenr3+UYSwrAG1wOgigHRXp+LnAL3JDP3OAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMbNra+BX9Rriv1PBHAgEQgDsNbS2X/+3mMziwuzz7ysXU7VfqvmmffE9lH8Ih2+/2k+k7Lo2xl/AC9VbFUElZNlSnCpydQGvWKS9JsA==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2026-07-15T03:05:33Z"
    mac: ENC[AES256_GCM,data:UbfcD1+qlArDr2ZZvyPYwzXfXyT9H7S38jUIF17XIe9rrYkA8kJD1AcAONcA2K154ihB8IDgc7gH6y2IyUmbGjl7I4xbaAP+rIpGmb4jlF2FxMeZTceCSQQZL7O1/ymMPgL6PTPIwd4zJEon+26ixzltE09oJjt10YUomkacKew=,iv:RhGkJBTxZ0LniEd7xQOy6CyJ9WISI/hXb9rNOKv2Nsc=,tag:uqK7e91Y0JDD39la2JWY7w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
