apiVersion: v1
kind: Secret
metadata:
    name: acruet-cron
    namespace: acruet
type: Opaque
stringData:
    secret: ENC[AES256_GCM,data:8TAivpD4oBgVam3vblC2ptZPCsS1H/5VrJRnQhMXsZAOwJb6Sd1Yui+t8bg=,iv:4RLtp3e+IhblSWgaTus0h5PzXL0aMLUJ6ekN3gdQCLE=,tag:93X00YxuvrCBdhJ1JdSzHg==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:us-east-2:712671171381:alias/sops
          created_at: "2026-07-19T19:20:54Z"
          enc: AQICAHhjc7KqbSU4p0/AUwvgncJOvdI1500sgVLenr3+UYSwrAHGGiIH6EN7zhOXVVeiFtswAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMk0zsJlQZxifUeuW+AgEQgDvZMj8yYB/LvZtzLPZgcOPJ5cUxiCK3ZkVXqwQ47LxP5QdYpe3Zxe/FQZIiFSMEsbm25YfF4ysGbq7hcA==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2026-07-19T19:20:54Z"
    mac: ENC[AES256_GCM,data:VqCO5p3QHltVouSoL7nEHgGkOQ+zyZIviSYhBM4LBo7TN83oBRvJqidbcLXTGhwvAI1ZERvx6LaLuG9DMbJpYvsjQc07pIAkEkluVAWwR8xCInD38fzezZCjSkDhLjoUTLoKlG9TZZAox//ov2dX0+vPB1H2r3jNAVpvYcCvQsk=,iv:tqA3CD8rnJTyG6/qczu/lHvL+PlTqhMomziSYKgpAZs=,tag:re92VAy9lcUIhewfVINfiA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
