# Placeholder until Proton SMTP token is provisioned (ROLLOUT Phase 5).
# Edit with: sops iac/kustomize/acruet/base/secrets/acruet-smtp.yaml
apiVersion: v1
kind: Secret
metadata:
    name: acruet-smtp
    namespace: acruet
type: Opaque
stringData:
    host: ENC[AES256_GCM,data:YW7IIj13MTQD/MhwnbUt0wxj,iv:e41r3HWzy2Pw9vEhBYfO6RDZ8wWN5jV0oDI3XEzTRpY=,tag:TGjjM633dg/lLW18DDWlQA==,type:str]
    port: ENC[AES256_GCM,data:R3bi,iv:XXNRMQ9kJeBkb6Tly8d8dS8zhsLPsajK0/i9Pg51hQI=,tag:uHWP8TRDG3a58LkpEosAjA==,type:str]
    username: ENC[AES256_GCM,data:Daf+RjGcrOgkdgySHdMozdkQhIhHKk6S,iv:DTlUHx+lJhLH+BGnBkuIVlAAzX9P+F6XB9NNMCZZjvg=,tag:1zEwhBLO3kY/lQlra3CjkA==,type:str]
    password: ENC[AES256_GCM,data:h5drbdsase4KxM4v6HU2JUUgziaNbiWT7lEGBJ0l,iv:rNmLpmxndvgp7OySFIXl4YJlCuqkCAO/2xnuXpjl+eQ=,tag:Uhc2iUjMtpSZco2z1k4SFA==,type:str]
    from: ENC[AES256_GCM,data:qToWmCLevLgrLJAE7riSVUUWNn7OHSpx,iv:amzORzsVeFZnigrTYjSxu0o35VJqZDSFbD9eyJk4XWc=,tag:JTK1tUKCoGxnj29faTRjfg==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:us-east-2:712671171381:alias/sops
          created_at: "2026-07-13T00:27:37Z"
          enc: AQICAHhjc7KqbSU4p0/AUwvgncJOvdI1500sgVLenr3+UYSwrAHaVjEe3lOSJ0syYr2hJ6RFAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMDgaHQb8/JNNB5zuiAgEQgDti5CFCT2zBmrjFeH3i6ImNaNLAs9OIxNO0EmOnY9S1qmn3PMMK1sE9DR11s4Sx5CqisniDUZrC3xM5fA==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2026-07-13T00:27:37Z"
    mac: ENC[AES256_GCM,data:AmzFcXwStRAHaxnVgMwliXhtvQBR5REcEqKzf73PQOnWLA2w0GVZq5mnCLgE9p4bmE/CjscBrxIcYDZ9zgAKVveBzMkrXfAsWC/pXs+eVPoKdBUlW9N3+nJwSHKj/2hpnGZd79DBtD6Jf7I3/mraXlzNhieDxWYIicyAGrVkRUc=,iv:noIirlAu7i0gav31Clxz9o4BVYCarQEmKz6iHPLhcUk=,tag:/83LvrPGO8ieFtcXcq+Evg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
