apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: default

resources:
  - ../base

images:
  - name: sbwise/wise-home-index
    newTag: 2.0.0

patches:
  - target:
      kind: Deployment
    path: patches/deployment.yaml
