applications:
  - name: Flask Hello World
    url: https://flask-hello-world.home.bradandmarsha.com/
    image: https://media.home.bradandmarsha.com/media/flaskred.png

  - name: Ceph Dashboard
    url: https://ceph-dashboard/
    image: https://media.home.bradandmarsha.com/media/ceph.svg

  - name: Grafana Dashboard
    url: https://grafana-dashboard/
    image: https://media.home.bradandmarsha.com/media/grafana.jpg

  - name: Wise k8s Plex
    url: https://plex.home.bradandmarsha.com/
    image: https://media.home.bradandmarsha.com/media/plex-icon-filled-256.png
