applications:
  - name: Flask Hello World
    url: http://flask-hello-world.home.bradandmarsha.com/

  - name: Ceph Dashboard
    url: http://ceph-dashboard
  
  - name: Wise k8s Plex
    url: http://wise-plex-k8s
