applications:
  - name: Flask Hello World
    url: https://flask-hello-world.home.bradandmarsha.com/

  - name: Ceph Dashboard
    url: https://ceph-dashboard/

  - name: Wise k8s Plex
    url: https://wise-plex-k8s/
