apiVersion: ceph.rook.io/v1
kind: CephCluster
metadata:
  name: rook-ceph
  namespace: rook-ceph
spec:
  dashboard:
    prometheusEndpoint: http://prometheus-stack-kube-prom-prometheus.monitoring.svc:9090
    prometheusEndpointSSLVerify: false
  monitoring:
    enabled: true
  labels:
    monitoring:
      release: prometheus-stack
