# Confidential client secret for KeycloakOIDCClient acruet.
# Generate: openssl rand -base64 32
# Edit: sops iac/kustomize/keycloak/base/secrets/acruet-oidc-client.yaml
# Copy client-secret value to acruet/base/secrets/acruet-oidc.yaml (client-secret key).
apiVersion: v1
kind: Secret
metadata:
    name: acruet-oidc-client
    namespace: keycloak
type: Opaque
stringData:
    client-secret: ENC[AES256_GCM,data:hWSJ6jRgzf3JGcdHtf/onYGW7MBcgfK1pQiTeVoLN4uoLAhnbCQkJEqP4ZM=,iv:nCqvcmpxEFkYw7G4siFdqWcvD4Yg/fiIUCAG9TDLBhU=,tag:88MS1QgUj+oDXCfUBWvFhw==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:us-east-2:712671171381:alias/sops
          created_at: "2026-07-13T01:10:48Z"
          enc: AQICAHhjc7KqbSU4p0/AUwvgncJOvdI1500sgVLenr3+UYSwrAHcOOoVSnnhJL20466ICJs+AAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMlidlIXa79wdu3l8MAgEQgDvCb3Ysd3txvnNJTFQg6V6AT7HOSRHNAOnq6YxWobNoSdQuNeY4IkVTLMonMGoNPBHiYdybs9xbAtvSgw==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2026-07-13T01:10:48Z"
    mac: ENC[AES256_GCM,data:C2WQfL3h8NH4DXNUCd52QhxioQyx/IevhRnWZhdK+DuXvZGMwADCzTxZdd9lFhwcmryXDoGtOM3q9J3aQR6ILDmnxBqbhifzg1oEzCxAmPlPvG6UO4uHY2fxUj1KL+1XJ5Q6KgLqWS76paehqrrhmKBLGPMe3bLX0JFD+haz8So=,iv:T7Ps8LetKM2jgCMP9GUq4WgB4VOZUaNLZDXmpqICxLY=,tag:ip9ghUljRrF+T9QTeuouRQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
