apiVersion: v1
kind: Secret
metadata:
    name: keycloak-smtp
    namespace: keycloak
type: Opaque
stringData:
    host: ENC[AES256_GCM,data:nCaMI5w7N2JZI7o56D2YrcI8,iv:VfKPKMNkeI2NsY/4m6jSWU4K3CJXPbVtL8hJl7JiZaI=,tag:EGurVNFEIC/GsLuSBPyYMg==,type:str]
    port: ENC[AES256_GCM,data:dhrT,iv:DMzGVoyM1u8GJUxZ+EyXu/TzEqi23IsAtVlDFsVGZcM=,tag:Wxa5NmTxJZJMbNDH5Bz83Q==,type:str]
    username: ENC[AES256_GCM,data:KyUf004ip3SzDxIrE8jrqHnMLNYKYCPp,iv:JzVN1NdHYBCI7968WDc7vv22ahkK4OoH0fuhsQnzbjg=,tag:CBcAZSo5C8QhaeJZLlVZ/g==,type:str]
    password: ENC[AES256_GCM,data:vpPcPCVJ2BH0hY0u0zVpFw==,iv:WVORXOEBcqXHLjwkEPgEMzrVIu/LZ3M3/9SUJZepDhk=,tag:uHpA3xKrIBHkVT9Tbnx1wQ==,type:str]
    from: ENC[AES256_GCM,data:nKJj/M6LErEULmiL1ubTeMYv1SvOZD4h,iv:hysfdtPCQZK7BoucqX1s2GzZUPike4Aqke04oGsI02A=,tag:Zd7BfAUu51qN8diO3+1yGw==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:us-east-2:712671171381:alias/sops
          created_at: "2026-07-18T19:19:24Z"
          enc: AQICAHhjc7KqbSU4p0/AUwvgncJOvdI1500sgVLenr3+UYSwrAEtiMyPs5E392npUlBWEEYFAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMirdJJzc5Y/llD2oyAgEQgDvtwV1wIQ1r9CDPKZN85dIloKO6L2P20zPIdlOmiHwL8D53O3G5zmCVYpeWKSdxj2r3YhTnwgKgn6obmQ==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2026-07-18T19:19:25Z"
    mac: ENC[AES256_GCM,data:TYgFFiLodPUrff2KtCnuHsWMFgHGy79btK5nRYB8TLA2a90geznQjdDta8H5zL4m3+0ouqgwhlrw2+MXVxA5c8PkfXn48Pi1tJUU+/kPwQTnqHFk7HGrsBb/zCKa0sbKe3iaIpN4NZT6JgboPyslRtZsX7xo2mCn8nw4nvNULOU=,iv:5RQRd4s9F6hlqVvSnoRO6wPZ2Cnp5mgzXz3p4817DfM=,tag:PmYF/4S5im9wsrn6oEqO1Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
