apiVersion: v1
kind: Secret
metadata:
    name: keycloak-admin
    namespace: keycloak
type: Opaque
stringData:
    client-id: ENC[AES256_GCM,data:MKoQcGogsbllhOt+YCky8h0=,iv:sHPEXw+m/VbKRvEG+uFRmzLEXsbZbAL8w2yStAQs46U=,tag:ErUF/NJquHIm+A6dyvjm0Q==,type:str]
    client-secret: ENC[AES256_GCM,data:QgohgXN9auAsBc16P/9ZTsa1/SFSC9EnEKvhDv9jccu3ezIo4aJJHQG2aNWpxSnE+K5FRZLPhwDFdMPPugorCED4APqsyg6ENVvUram39rmj2hcHFfM=,iv:Es2il/sqaQrlJ4BdY0DuatUgg7WObRh2dR4UrG6ayug=,tag:KRHIviUU/Fh/0rb7QQtmYQ==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:us-east-2:712671171381:alias/sops
          created_at: "2026-07-13T02:02:18Z"
          enc: AQICAHhjc7KqbSU4p0/AUwvgncJOvdI1500sgVLenr3+UYSwrAFc1WgnY7QTN9y5Uy/3WRt9AAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMoGB6+keoh5pI+X7kAgEQgDuKBTBeHJVh/eSLWhW/QYWwXF78/4wl+C5tPHGjBfmup3aZw9Izs21bMITtK+QLs5wMOwRCN+atErimJA==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2026-07-13T02:02:18Z"
    mac: ENC[AES256_GCM,data:nns/Kix9K4Ef7QcLAcVVXiiGwQWiI83+d4udY5XwQZl0/1u2NP8cFoPNjp39mcu4Vs5yuTBap7Cc6YaN97gtYs/lE0XHxi1zBf5r5HP+XJ1xE0javw12wmzjNx97mYg6HCtwLlOrgx8Y87lMqU48iAltBuWylfM7YfW3uLgjOoQ=,iv:FTJWpFQ1ouR+0A6UxXpKSZbeo9KVJmh/ZArBpr09/y0=,tag:viNDr+69NVR0O99HruAHAA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
