apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - flux-instance.yaml
  - namespace.yaml
  - operator.yaml
  - certificate.yaml
  - ingress.yaml
  - httproute.yaml
  - referencegrant-gateway-tls.yaml
  - networkpolicy-flux-web-ingress.yaml
patches:
  - path: patches/flux-sops-irsa.yaml
