apiVersion: v1
kind: ConfigMap
data:
  config.json: |-
    [
      {
        "clusterID": "aa51c178-5d12-46eb-b74c-3440fb71fe7b",
        "monitors": [
          "10.96.65.117:6789",
          "10.107.84.148:6789",
          "10.103.11.115:6789"
        ]
      }
    ]
metadata:
  name: ceph-csi-config
  namespace: default
