apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../base/v1.19.0
  - certificate.yaml
  - cert-issuer.yaml
  - csi-kms-config-map.yaml
  - ceph-config-map.yaml
  - csi-rbdplugin-provisioner.yaml
  - csi-rbdplugin.yaml
  - csi-rbd-sc.yaml
  - ingress.yaml
  - toolbox.yaml

patches:
  - path: patches/csi-nodeplugin-rbac.yaml
  - path: patches/csi-provisioner-rbac.yaml
