apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../base/v1.19.5
  - ceph-config-map.yaml
  - certificate.yaml
  - csi-kms-config-map.yaml
  - csi-nodeplugin-sa.yaml
  - csi-provisioner-sa.yaml
  - csi-rbdplugin-provisioner.yaml
  - csi-rbdplugin.yaml
  - csi-rbd-sc.yaml
  - ingress.yaml
  - httproute.yaml
  - referencegrant-gateway-tls.yaml
  - backendconfig-ceph-dashboard.yaml
  - toolbox.yaml
  - monitoring-rbac.yaml
  - prometheus-ceph-rules.yaml
  - dashboard-alertmanager-config-cronjob.yaml

patches:
  - target:
      kind: CephCluster
      name: rook-ceph
    path: patches/ceph-monitoring.yaml
  - target:
      kind: ClusterRole
      name: rbd-csi-nodeplugin
    path: patches/csi-nodeplugin-cluster-role.yaml
  - target:
      kind: ClusterRoleBinding
      name: rbd-csi-nodeplugin
    path: patches/csi-nodeplugin-cluster-role-binding.yaml
  - target:
      kind: ClusterRole
      name: rbd-external-provisioner-runner
    path: patches/csi-provisioner-cluster-role.yaml
  - target:
      kind: ClusterRoleBinding
      name: rbd-csi-provisioner-role
    path: patches/csi-provisioner-cluster-role-binding.yaml
  - target:
      kind: Role
      name: rbd-external-provisioner-cfg
    path: patches/csi-provisioner-role.yaml
  - target:
      kind: RoleBinding
      name: rbd-csi-provisioner-role-cfg
    path: patches/csi-provisioner-role-binding.yaml
