---
apiVersion: v1
kind: Namespace
metadata:
  name: route53-ddns
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: route53-ddns
  namespace: route53-ddns
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::712671171381:role/route53-ddns
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: route53-ddns
  namespace: route53-ddns
spec:
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: route53-ddns
  template:
    metadata:
      labels:
        app: route53-ddns
    spec:
      serviceAccountName: route53-ddns
      containers:
      - name: route53-ddns
        image: sbwise/route53-ddns:1.0.0
        resources:
          limits:
            memory: '64Mi'
            cpu: '50m'
        env:
        - name: R53_DOMAIN
          value: 'home.bradandmarsha.com'
        - name: R53_HOSTED_ZONE_ID
          value: 'Z05560511DSPWIB0LNUUD'
        - name: R53_TTL
          value: '3600'
        - name: AWS_REGION
          value: 'us-east-2'
