apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - ../base/0.91.0
  - certificate.yaml

patches:
  - target:
      kind: Ingress
      name: prometheus-stack-grafana
    path: patches/ingress.yaml
  - target:
      kind: Deployment
      name: prometheus-stack-grafana
    path: patches/grafana-domain.yaml
  - target:
      kind: Prometheus
      name: prometheus-stack-kube-prom-prometheus
    path: patches/prometheus-external-labels.yaml
  - target:
      kind: Service
      name: prometheus-stack-kube-prom-coredns
    path: patches/kube-system-exporter-service.yaml
  - target:
      kind: Service
      name: prometheus-stack-kube-prom-kube-controller-manager
    path: patches/kube-system-exporter-service.yaml
  - target:
      kind: Service
      name: prometheus-stack-kube-prom-kube-etcd
    path: patches/kube-system-exporter-service.yaml
  - target:
      kind: Service
      name: prometheus-stack-kube-prom-kube-proxy
    path: patches/kube-system-exporter-service.yaml
  - target:
      kind: Service
      name: prometheus-stack-kube-prom-kube-scheduler
    path: patches/kube-system-exporter-service.yaml
